### ISSUE TITLE
"invalid pointer" error on exit

### ISSUE THREAD

**Issue by piotrkochan** [dvorka/hstr#330] opened 2018-11-30 11:56 UTC
HSTR always report an error on shutdown, for example after "escape or ctrl+c" or entry select:

```free(): invalid pointer
[1]    9926 abort (core dumped)  hstr
```

```lsb_release -a
lsb_release -a  
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

```zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)```

**Comment by dvorka** [comment] 2018-12-02 17:02
@piotrkochan thank you for reporting the bug! Can you please add/attach:

* `hstr --version`
* `uname -a`

Unfortunately I'm unable to reproduce the problem (running the same version of Ubuntu as you on my machine), could you please use `strace` (or any similar tool):
```
strace hh 2> error.log
```
... and share error.log with me so that I can find out more details?

Perhaps the problem might be that you have something specific in your history and/or system. I you don't mind, could you create a new user and try HSTR there (with empty history)? Any diacritics, non-US locals, etc. what makes your system special?

Thank you for your interest in HSTR and help!

**Comment by piotrkochan** [comment] 2018-12-02 17:03
Sure, I'll provide these details tomorrow. There is no error on my home computer.

**Comment by dvorka** [comment] 2018-12-02 17:08
Thanks - really appreciate it :wink:

**Comment by piotrkochan** [comment] 2018-12-03 06:35
```
hstr version "2.0.0" (2018-08-28T13:30:00)
```

```uname -a
Linux kochan-pc 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Strace:

```
execve("/usr/bin/hh", ["hh"], 0x7fff870ef3f0 /* 142 vars */) = 0
brk(NULL)                               = 0x56246c075000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=222878, ...}) = 0
mmap(NULL, 222878, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f564cdc5000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libreadline.so.7", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2208\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=294632, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f564cdc3000
mmap(NULL, 2395240, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f564c98c000
mprotect(0x7f564c9cd000, 2093056, PROT_NONE) = 0
mmap(0x7f564cbcc000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x40000) = 0x7f564cbcc000
mmap(0x7f564cbd4000, 3176, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f564cbd4000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\272\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1700792, ...}) = 0
mmap(NULL, 3789144, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f564c5ee000
mprotect(0x7f564c78b000, 2093056, PROT_NONE) = 0
mmap(0x7f564c98a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19c000) = 0x7f564c98a000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libncursesw.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340q\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=190400, ...}) = 0
mmap(NULL, 2286072, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f564c3bf000
mprotect(0x7f564c3ec000, 2097152, PROT_NONE) = 0
mmap(0x7f564c5ec000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2d000) = 0x7f564c5ec000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libtinfo.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\311\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=170784, ...}) = 0
mmap(NULL, 2267936, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f564c195000
mprotect(0x7f564c1ba000, 2097152, PROT_NONE) = 0
mmap(0x7f564c3ba000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x25000) = 0x7f564c3ba000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2030544, ...}) = 0
mmap(NULL, 4131552, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f564bda4000
mprotect(0x7f564bf8b000, 2097152, PROT_NONE) = 0
mmap(0x7f564c18b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e7000) = 0x7f564c18b000
mmap(0x7f564c191000, 15072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f564c191000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14560, ...}) = 0
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f564bba0000
mprotect(0x7f564bba3000, 2093056, PROT_NONE) = 0
mmap(0x7f564bda2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f564bda2000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f564cdc1000
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f564cdbe000
arch_prctl(ARCH_SET_FS, 0x7f564cdbe740) = 0
mprotect(0x7f564c18b000, 16384, PROT_READ) = 0
mprotect(0x7f564bda2000, 4096, PROT_READ) = 0
mprotect(0x7f564c3ba000, 16384, PROT_READ) = 0
mprotect(0x7f564c5ec000, 4096, PROT_READ) = 0
mprotect(0x7f564c98a000, 4096, PROT_READ) = 0
mprotect(0x7f564cbcc000, 8192, PROT_READ) = 0
mprotect(0x56246b29b000, 4096, PROT_READ) = 0
mprotect(0x7f564cdfc000, 4096, PROT_READ) = 0
munmap(0x7f564cdc5000, 222878)          = 0
brk(NULL)                               = 0x56246c075000
brk(0x56246c096000)                     = 0x56246c096000
openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=4252880, ...}) = 0
mmap(NULL, 4252880, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f564b791000
close(3)                                = 0
brk(0x56246c0bf000)                     = 0x56246c0bf000
access("/home/kochan/.hstr_favorites", F_OK) = 0
openat(AT_FDCWD, "/home/kochan/.hstr_favorites", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=24, ...}) = 0
fstat(3, {st_mode=S_IFREG|0664, st_size=24, ...}) = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "git log --color --graph\n", 24) = 24
lseek(3, 24, SEEK_SET)                  = 24
close(3)                                = 0
openat(AT_FDCWD, "/home/kochan/.zsh_history", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=535138, ...}) = 0
mmap(NULL, 536576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f564cd3b000
read(3, ": 1513597484:0;sudo service kiba"..., 535138) = 535138
close(3)                                = 0
brk(0x56246c0e0000)                     = 0x56246c0e0000
brk(0x56246c102000)                     = 0x56246c102000
brk(0x56246c126000)                     = 0x56246c126000
brk(0x56246c14b000)                     = 0x56246c14b000
brk(0x56246c170000)                     = 0x56246c170000
brk(0x56246c192000)                     = 0x56246c192000
brk(0x56246c1bc000)                     = 0x56246c1bc000
brk(0x56246c1ec000)                     = 0x56246c1ec000
brk(0x56246c1dd000)                     = 0x56246c1dd000
brk(0x56246c202000)                     = 0x56246c202000
brk(0x56246c22b000)                     = 0x56246c22b000
brk(0x56246c25a000)                     = 0x56246c25a000
munmap(0x7f564cd3b000, 536576)          = 0
getppid()                               = 28005
openat(AT_FDCWD, "/proc/28005/comm", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(3, "strace\n", 1024)               = 7
read(3, "", 1024)                       = 0
close(3)                                = 0
brk(0x56246c288000)                     = 0x56246c288000
brk(0x56246c2a9000)                     = 0x56246c2a9000
brk(0x56246c2ca000)                     = 0x56246c2ca000
brk(0x56246c2eb000)                     = 0x56246c2eb000
brk(0x56246c30c000)                     = 0x56246c30c000
brk(0x56246c32d000)                     = 0x56246c32d000
brk(0x56246c34e000)                     = 0x56246c34e000
brk(0x56246c36f000)                     = 0x56246c36f000
brk(0x56246c390000)                     = 0x56246c390000
brk(0x56246c3b1000)                     = 0x56246c3b1000
brk(0x56246c3d2000)                     = 0x56246c3d2000
brk(0x56246c3f3000)                     = 0x56246c3f3000
brk(0x56246c414000)                     = 0x56246c414000
brk(0x56246c435000)                     = 0x56246c435000
brk(0x56246c456000)                     = 0x56246c456000
brk(0x56246c477000)                     = 0x56246c477000
brk(0x56246c498000)                     = 0x56246c498000
brk(0x56246c4c1000)                     = 0x56246c4c1000
rt_sigaction(SIGINT, {sa_handler=0x56246b094fc0, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
stat("/home/kochan/.terminfo", 0x56246c4626e0) = -1 ENOENT (No such file or directory)
stat("/etc/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/lib/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
access("/etc/terminfo/x/xterm-256color", R_OK) = -1 ENOENT (No such file or directory)
access("/lib/terminfo/x/xterm-256color", R_OK) = 0
openat(AT_FDCWD, "/lib/terminfo/x/xterm-256color", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=3525, ...}) = 0
read(3, "\32\1%\0&\0\17\0\235\1\2\6xterm-256color|xterm"..., 4096) = 3525
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=32, ws_col=135, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=32, ws_col=135, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig -icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig -icanon echo ...}) = 0
ioctl(1, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
rt_sigaction(SIGTSTP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=0x56246b094fc0, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x7f564c3d74a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
rt_sigaction(SIGWINCH, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGWINCH, {sa_handler=0x7f564c3d7490, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
ioctl(1, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
write(1, "\33[?1049h\33[22;0;0t\33[1;32r\33(B\33[m\33["..., 46) = 46
brk(0x56246c4e2000)                     = 0x56246c4e2000
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
write(1, "\33[39;49m\33[39;49m\33(B\33[m\33[H\33[2J\33[4"..., 35) = 35
write(1, "git s\r\33[5d ", 11)          = 11
write(1, "ls -l\r\33[6d ", 11)          = 11
write(1, "ci\33[7d\10\10", 8)           = 8
write(1, "sudo service apache2 restart\r\33[8"..., 34) = 34
write(1, "c install\r\33[9d ", 15)      = 15
write(1, "rm -rf tmp/Kernel/Cache/*\r\33[10d ", 32) = 32
write(1, "composer require friendsofsymfon"..., 112) = 112
write(1, "nano ~/.zsh_aliases\r\33[12d ", 26) = 26
write(1, "git log --color --graph\r\33[13d ", 30) = 30
write(1, "git stash\r\33[14d ", 16)     = 16
write(1, "#12 /media/sdb1/dev/tme_v4/vendo"..., 140) = 140
write(1, "rm -rf tmp/Kernel/Cache/*; echo "..., 42) = 42
write(1, "composer require --prefer-stable"..., 128) = 128
write(1, "git stash pop\r\33[18d ", 20) = 20
write(1, "git add .\r\33[19d ", 16)     = 16
write(1, "\\\33[20d\10", 7)             = 7
write(1, "git diff\r\33[21d ", 15)      = 15
write(1, "git push\r\33[22d ", 15)      = 15
write(1, "git reset --hard\33[23;4H", 23) = 23
write(1, "--enable-embedded-mysqli \\\\\r\33[24"..., 34) = 34
write(1, "#13 /media/sdb1/dev/tme_v4/bin/c"..., 140) = 140
write(1, "--with-freetype-dir \\\\\r\33[26d ", 29) = 29
write(1, "git ch feature/TME-1748-przekier"..., 64) = 64
write(1, "--enable-mbstring \\\\\r\33[28d ", 27) = 27
write(1, "php -v\r\33[29d ", 13)        = 13
write(1, "bin/console tme:sitemap:build pa"..., 61) = 61
write(1, "--with-jpeg-dir \\\\\33[31;5H", 25) = 25
write(1, "-d queries=\"[{\\\"mpn\\\":\\\"SN74S74N"..., 47) = 47
write(1, "--with-png-dir \\\\", 17)     = 17
write(1, "\33(B\33[m", 6)               = 6
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
write(1, "\r\33[2d", 5)                 = 5
write(1, "Type to filter, UP/DOWN move, RE"..., 86) = 86
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
write(1, "\r\33[3d", 5)                 = 5
write(1, "\33(B\33[0;1;7m- HISTORY - view:rank"..., 152) = 152
write(1, "\33(B\33[m", 6)               = 6
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
access("/proc/sys/kernel/hostname", F_OK) = 0
openat(AT_FDCWD, "/proc/sys/kernel/hostname", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(3, "kochan-pc\n", 1024)            = 10
close(3)                                = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
write(1, "\33[H", 3)                    = 3
write(1, "\33(B\33[0;1m\33[34mkochan@kochan-pc$ ", 32) = 32
write(1, "\33[39m\33(B\33[m", 11)       = 11
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
read(0, "\33", 1)                       = 1
poll([{fd=0, events=POLLIN}], 1, 5)     = 0 (Timeout)
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
write(1, "\33[2;87H", 7)                = 7
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
write(1, "\33[H\33[2J", 7)              = 7
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
poll([{fd=0, events=POLLIN}], 1, 0)     = 0 (Timeout)
rt_sigaction(SIGTSTP, {sa_handler=0x7f564c3d7590, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f564bde2f20}, NULL, 8) = 0
write(1, "\33[32;1H\33[?1049l\33[23;0;0t\r\33[?1l\33>", 32) = 32
ioctl(1, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(1, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
writev(2, [{iov_base="free(): invalid pointer", iov_len=23}, {iov_base="\n", iov_len=1}], 2free(): invalid pointer
) = 24
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f564cdfb000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 28007
gettid()                                = 28007
tgkill(28007, 28007, SIGABRT)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=28007, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
```

**Comment by dvorka** [comment] 2019-12-21 08:39
Seems like an attempt to free invalid/already freed/NULL pointer:
```
writev(2, [{iov_base="free(): invalid pointer", iov_len=23}, {iov_base="\n", iov_len=1}], 2free(): invalid pointer
) = 24
```

**Comment by dvorka** [comment] 2019-12-21 17:04
It might be fixed by e9452d2 released as HSTR `2.2`, please verify.

**Comment by piotrkochan** [comment] 2020-01-03 06:27
@dvorka Looks like it's working now (Ubuntu 19, ZSH)

**Comment by dvorka** [comment] 2020-01-03 07:08
@piotrkochan thank you for the verification and letting me know :wink:

**Closed by dvorka** 2020-01-03 07:08 UTC
Labels: % zsh, :beetle: bug, :hurtrealbad: major, done
