### ISSUE TITLE
zsh history should only be truncated when EXTENDED_HISTORY is enabled

### ISSUE THREAD

**Issue by hvindin** [dvorka/hstr#274] opened 2018-06-07 13:29 UTC
As per the zsh man pages:

>        EXTENDED_HISTORY <C>
> 
>               Save each command's beginning timestamp (in seconds since the epoch) and the duration (in seconds) to the history file.  The format of this prefixed data is:
> 
>               `: <beginning time>:<elapsed seconds>;<command>'.

By the looks of the code [here](https://github.com/dvorka/hstr/blob/master/src/hstr_history.c#L146-L150):
```C
if(historyList[i]->line && strlen(historyList[i]->line)>itemOffset) {
    line=historyList[i]->line+itemOffset;
} else {
    line=historyList[i]->line;
}
```

and [here](https://github.com/dvorka/hstr/blob/master/src/hstr_history.c#L78-L91):
```C
int get_item_offset(void)
{
    if(isZshParentShell()) {
        // In zsh history file, the format of item is
        // [:][blank][unix_timestamp][:][0][;][cmd]
        // Such as:
        // : 1420549651:0;ls /tmp/b
        // And the limit of unix timestamp 9999999999 is 2289/11/21,
        // so we could skip first 15 chars in every zsh history item to get the cmd.
        return ZSH_HISTORY_ITEM_OFFSET;
    } else {
        return BASH_HISTORY_ITEM_OFFSET;
    }
}
```

There's no consideration given to zsh history which *doesn't* use the EXTENDED_HISTORY option. So for me, looking at my history, it's basically non-sensical because the first 15 characters seem to have been trimmed and I don't have EXTENDED_HISTORY enabled.

![Truncated hh](https://gist.githubusercontent.com/hvindin/dcbd0c7592bbc14de7a154e33b3e25ad/raw/47dbb51004f4d0d13f906cbdbc99ca129928e6c6/truncated-hh-terminal.png)

**Comment by dvorka** [comment] 2018-08-13 14:46
Duplicate of #296 (my fault) fixed by commit 3e8ed35165dbf267911d17e30dc39b32d1af76ab

**Closed** 2018-08-13 14:47 UTC
Labels: % zsh, :beetle: bug, :hurtrealbad: major
