### ISSUE TITLE
Error installing on Arch via AUR

### ISSUE THREAD

**Issue by thiagomeireless** [dvorka/hstr#434] opened 2021-11-08 00:05 UTC
Hello! I've been trying to install this via AUR but been getting this error:

```
....
gcc -DPACKAGE_NAME=\"hstr\" -DPACKAGE_TARNAME=\"hstr\" -DPACKAGE_VERSION=\"2.3.0\" -DPACKAGE_STRING=\"hstr\ 2.3.0\" -DPACKAGE_BUGREPORT=\"martin.dvorak@mindforger.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hstr\" -DVERSION=\"2.3.0\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_LIBNCURSESW=1 -DHAVE_LIBM=1 -DHAVE_LIBREADLINE=1 -DHAVE__BOOL=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -I.    --pedantic -Wall -std=c99 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -MT hstr.o -MD -MP -MF .deps/hstr.Tpo -c -o hstr.o hstr.c
hstr.c: In function ‘print_cmd_added_favorite_label’:
hstr.c:743:44: error: format not a string literal and no format arguments [-Werror=format-security]
  743 |     mvprintw(hstr->promptYNotification, 0, screenLine);
      |                                            ^~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [Makefile:411: hstr.o] Error 1
make[1]: Leaving directory '/home/thiago/.cache/yay/hstr-git/src/hstr-git/src'
make: *** [Makefile:407: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hstr-git
```

Is this a known problem?

**Comment by epsilon77** [comment] 2021-11-09 01:47
Hello! 

I think this patch fix the problem 
https://salsa.debian.org/debian/hstr/-/blob/master/debian/patches/04_fix_ftbfs_string_format_error.diff

**Comment by dvorka** [comment] 2021-12-03 23:07
@epsilon77 @thiagomeireless https://github.com/dvorka/hstr/pull/435 is fix for this issue. I didn't want to merge it as I afraid of breaking the build on other distribution. This problem seems to be reproducible on latest ncurses (while most of the distributions have older version). I will probably have to do conditional compilation...

**Comment by dvorka** [comment] 2021-12-14 06:13
I fixed this issue in [xxx](https://github.com/dvorka/hstr/commit/9152b59527b5fcc5d4de89945b3c40fe49a42ba2#diff-b0ed02652c9e84bbf54e376e081b422d224046e14228255d65c9ff066e617a41R745) - see also https://aur.archlinux.org/packages/hstr/

**Closed** 2021-12-14 06:13 UTC
Labels: arch

**Comment by thiagomeireless** [comment] 2021-12-14 13:47
Thank you! Worked perfectly 👍🏻
